name: ExtDN Integration Tests
on: [pull_request]

jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_SQL_TO_RUN: 'GRANT ALL ON *.* TO "root"@"%";'
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: M2 Integration Tests on 2.3.7-p3
        uses: MultiSafepay/github-actions-m2/magento-integration-tests/7.3@with-coverage-support
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
            GLOBAL_GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
            COMPOSER_NAME: multisafepay/magento2
            PHPUNIT_FILE: .github/workflows/phpunit.xml
            CE_VERSION: 2.3.7-p3
            CURRENT_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        with:
            magento_pre_install_script: .github/workflows/magento-integration-tests-pre-phpunit.sh
            phpunit_file: .github/workflows/phpunit.xml
